### GET /api/donaciones recupera todas las donaciones
GET http://localhost:3000/api/donaciones

### GET /api/donaciones/:id recupera una donación
GET http://localhost:3000/api/donaciones/1

### GET /api/campanas/:id recupera una campaña - NOT FOUND(404)
GET http://localhost:3000/api/donaciones/50

### GET /api/donaciones/ con parametros recupera todas las donaciones que cumplen los filtros
### id_campana=1
GET http://localhost:3000/api/donaciones?id_campana=1
### nombre_donante=J
GET http://localhost:3000/api/donaciones?nombre_donante=J
### peso_donante_min=90
GET http://localhost:3000/api/donaciones?peso_donante_min=90
### peso_donante_max=120
GET http://localhost:3000/api/donaciones?peso_donante_max=80
### peso_donante_min y peso_donante_max
GET http://localhost:3000/api/donaciones?peso_donante_min=90&peso_donante_max=120
### fecha_donacion_min=
GET http://localhost:3000/api/donaciones?fecha_donacion_min=2024-03-02
### fecha_donacion_max=
GET http://localhost:3000/api/donaciones?fecha_donacion_max=2024-03-02
### fecha_donacion_min y fecha_donacion_max
GET http://localhost:3000/api/donaciones?fecha_donacion_min=2024-01-25&fecha_donacion_max=2024-03-02
### es_primera_vez=
GET http://localhost:3000/api/donaciones?es_primera_vez=true
### grupo_sanguineo=
GET http://localhost:3000/api/donaciones?grupo_sanguineo=0-

### POST /api/donaciones/ crea una donación 
POST http://localhost:3000/api/donaciones
Content-Type: application/json

{
    "id_campana": 1,
    "nombre_donante": "Laura borrar",
    "peso_donante": "65.50",
    "fecha_donacion": "2024-03-02",
    "es_primera_vez": false,
    "grupo_sanguineo": "0+"
}

### Borrado de un campaña que no existe (404)
DELETE http://localhost:3000/api/donaciones/19

### Borrado de un campaña
DELETE http://localhost:3000/api/donaciones/11

### Actualización de un campaña
PUT http://localhost:3000/api/donaciones/12
Content-Type: application/json

{
    "id_donacion": 12,
    "id_campana": 1,
    "nombre_donante": "Laura borrar",
    "peso_donante": "65.50",
    "fecha_donacion": "2024-03-02",
    "es_primera_vez": true,
    "grupo_sanguineo": "0-"
}